### ISSUE TITLE
feat: user guide for testnet

### ISSUE THREAD

**Issue by yehjxraymond** [BluejayFinance/docs#2]

**Comment by yehjxraymond** [comment]
See: https://www.notion.so/bluejay/Test-Net-Launch-7th-Apr-ecb6f7e0c1dc40bda8ac735bf8dace95

**Comment by yehjxraymond** [comment]
Start off in notion then move to docs later

**Comment by shreyabluejay** [comment]
Draft Testnet User Guide: https://www.notion.so/bluejay/User-Guides-8e5b010ce7ca4a2890bf616b1860e5e6
